### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by masayukiimai** [masayukiimai/furima-39626#1]
https://protospace-39626-2.onrender.com/prototypes/3

**Comment by shodai-ito** [comment]
@masayukiimai さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`ユーザー管理機能`**
- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
不要な箇所に「こんにちは、〇〇さん」の表示があるため削除をお願いします。
<img width="481" alt="スクリーンショット 2023-09-18 9 16 58" src="https://github.com/masayukiimai/furima-39626/assets/62537107/646431cf-7df3-495c-b589-c91b49463bb0">

### **`コメント機能`**
- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のフォームを送信すると、エラー画面になってしまいます。

### **`ユーザー詳細機能`**
- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザー詳細ページが正しく実装されていません。
<img width="1024" alt="スクリーンショット 2023-09-18 9 19 20" src="https://github.com/masayukiimai/furima-39626/assets/62537107/3ad2c338-6d28-4295-90ba-3fb74fead2f7">

### **`その他`**
- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他人のプロトタイプも編集できてしまいます。
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。

また、全体的にレイアウトの崩れが見られます。
達成要件には含まれませんが、見本アプリと比較してビューを整えると、よりユーザー体験がよくなるかと存じます。
<img width="586" alt="スクリーンショット 2023-09-18 9 26 02" src="https://github.com/masayukiimai/furima-39626/assets/62537107/22baad58-8141-4843-8ab2-8b6a53619411">
<img width="1198" alt="スクリーンショット 2023-09-18 9 26 37" src="https://github.com/masayukiimai/furima-39626/assets/62537107/1e2f6d22-c9d3-4689-aafc-230065895dbe">
<img width="1196" alt="スクリーンショット 2023-09-18 9 27 03" src="https://github.com/masayukiimai/furima-39626/assets/62537107/8e965882-1383-41ef-b027-c83c0c235bc1">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7
